task: emb_spatial_bench
dataset_path: "json"
dataset_kwargs:
  data_files:
    - ../../../datasets/EmbSpatial-Bench/embspatial_bench.json
test_split: train
output_type: generate_until

metric_list:
  - metric: score
    aggregation: !function utils.emb_spatial_aggregate_score
    higher_is_better: true

doc_to_visual: !function utils.emb_spatial_doc_to_visual
doc_to_text: !function utils.emb_spatial_doc_to_text
doc_to_target: !function utils.emb_spatial_doc_to_answer
process_results: !function utils.emb_spatial_process_results_generation
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer with the option's letter from the given choices directly."