include: _default_template_yaml
task: cosmos_robofail
dataset_name: robofail
test_split: benchmark
lmms_eval_specific_kwargs:
    sub_task: "robofail"
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."
metric_list:
  - metric: score
    aggregation: !function utils.cosmos_aggregate_score
    higher_is_better: true
